<?php

/**
 * ProcessWire module for restricting access to Page Edit tabs via permissions
 * by Adrian Jones
 *
 * Determine how pages are renamed when the title is changed
 *
 * ProcessWire 2.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class RestrictTabView extends WireData implements Module, ConfigurableModule {

    public static function getModuleInfo() {
        return array(
            'title' => 'Restrict Tab View',
            'summary' => 'Restrict access to Page Edit tabs via permissions',
            'author' => 'Adrian Jones',
            'href' => '',
            'version' => 8,
            'autoload' => 'template=admin',
            'requires' => 'ProcessWire>=2.5.16',
            'icon'     => 'toggle-on'
        );
    }


    /**
     * Data as used by the get/set functions
     *
     */
    protected $data = array();


   /**
     * Default configuration for module
     *
     */
    static public function getDefaultData() {
            return array(
                "viewTabs" => array(),
                "hideTabs" => array()
            );
    }

    /**
     * Populate the default config data
     *
     */
    public function __construct() {
       foreach(self::getDefaultData() as $key => $value) {
               $this->$key = $value;
       }
    }


    public function init() {
        $this->addHookAfter('ProcessPageEdit::buildFormContent', $this, "afterBuildFormContent");
        $this->addHookAfter('ProcessPageEdit::buildForm', $this, "afterBuildForm");
    }


    public function afterBuildForm(HookEvent $event){

        if($this->user->isSuperuser()) return;

        $form = $event->return;

        foreach($this->data['viewTabs'] as $tab) {
            if(!$this->user->hasPermission("tab-".strtolower($tab)."-view")) {
                $this->removeTabs($tab, $event);
            }
        }

        foreach($this->data['hideTabs'] as $tab) {
            if($this->user->hasPermission("tab-".strtolower($tab)."-hide")) {
                $this->removeTabs($tab, $event);
            }
        }

        $event->return = $form;
    }


    public function afterBuildFormContent (HookEvent $event) {

        if($this->user->isSuperuser()) return;

        // if settings tab is hidden for this user and name field is not set to be in the content tab, then we need to add it hidden
        if(
            (in_array("Settings", $this->data['viewTabs']) && !$this->user->hasPermission("tab-settings-view")) ||
            (in_array("Settings", $this->data['hideTabs']) && $this->user->hasPermission("tab-settings-hide"))
        ) {

            $form = $event->return;
            $p = $event->object->getPage();

            if(!$p->template->nameContentTab) {
                // name
                $field = $this->modules->get('InputfieldHidden');
                $field->attr('name', '_pw_page_name');
                $field->attr('value', $p->name);
                $field->required = $p->id != 1;
                $field->slashUrls = $p->template->slashUrls;
                if(!$p->editable('name')) {
                    $field->attr('disabled', 'disabled');
                    $field->required = false;
                }
                if($p->parent) $field->parentPage = $p->parent;
                $form->prepend($field);
            }

        }
    }


    public function removeTabs ($tab, $event) {

        $form = $event->return;

        if($tab == "Settings" || $tab == "Children" || $tab == "Delete") {
            $fieldset = $form->find("id=ProcessPageEdit".$tab)->first();
        }
        else {
            $fieldset = $form->find("id=ProcessPageEdit".$tab);
        }
        if(!is_object($fieldset)) return;

        $form->remove($fieldset);
        $event->object->removeTab("ProcessPageEdit".$tab);
    }





    /**
     * Return an InputfieldsWrapper of Inputfields used to configure the class
     *
     * @param array $data Array of config values indexed by field name
     * @return InputfieldsWrapper
     *
     */
    public static function getModuleConfigInputfields(array $data) {

        $data = array_merge(self::getDefaultData(), $data);

        $wrapper = new InputfieldWrapper();

        $f = wire('modules')->get('InputfieldCheckboxes');
        $f->attr('name+id', 'viewTabs');
        $f->label = __('View Tabs');
        $f->description = __("For non-superusers, the selected tabs will not be viewable unless they have a permission named tab-tabname-view, eg: tab-settings-view");
        $f->addOption("Children");
        $f->addOption("Settings");
        $f->addOption("Delete");
        $f->addOption("View");
        if(isset($data['viewTabs'])) $f->value = $data['viewTabs'];
        $wrapper->add($f);

        $f = wire('modules')->get('InputfieldCheckboxes');
        $f->attr('name+id', 'hideTabs');
        $f->label = __('Hide Tabs');
        $f->description = __("For non-superusers, the selected tabs will be hidden if they have a permission named tab-tabname-hide, eg: tab-settings-hide");
        $f->addOption("Children");
        $f->addOption("Settings");
        $f->addOption("Delete");
        $f->addOption("View");
        if(isset($data['hideTabs'])) $f->value = $data['hideTabs'];
        $wrapper->add($f);

        return $wrapper;
    }

}
